# Déploiement Gateway Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
  namespace: monapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
    spec:
      initContainers:
        - name: wait-for-backends
          image: busybox:1.28
          command: ['sh', '-c', 'until nc -z users-service 8001 && nc -z products-service 8002 && nc -z orders-service 8003; do echo "Waiting for backends..."; sleep 5; done']
      containers:
        - name: gateway-service
          image: d0eb58e49125.ngrok-free.app/deploy:15-gateway-service
          envFrom:
            - configMapRef:
                name: app-config
          env:
            - name: USERS_SERVICE_URL
              value: "http://users-service:8001"
            - name: PRODUCTS_SERVICE_URL
              value: "http://products-service:8002"
            - name: ORDERS_SERVICE_URL
              value: "http://orders-service:8003"
            - name: GATEWAY_ROUTES
              value: |
                /api/users=>http://users-service:8001,
                /api/products=>http://products-service:8002,
                /api/orders=>http://orders-service:8003
          ports:
            - containerPort: 8000
          readinessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 5