# Service PostgreSQL
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: monapp
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432



# Stockage persistant pour PostgreSQL
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: monapp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi



# Service Users
apiVersion: v1
kind: Service
metadata:
  name: users-service
  namespace: monapp
spec:
  selector:
    app: users-service
  ports:
    - port: 8001
      targetPort: 8001



# Service Orders
apiVersion: v1
kind: Service
metadata:
  name: orders-service
  namespace: monapp
spec:
  selector:
    app: orders-service
  ports:
    - port: 8003
      targetPort: 8003


# Service Products
apiVersion: v1
kind: Service
metadata:
  name: products-service
  namespace: monapp
spec:
  selector:
    app: products-service
  ports:
    - port: 8002
      targetPort: 8002



# Service Gateway (NodePort)
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: monapp
spec:
  type: NodePort
  selector:
    app: gateway-service
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 31083