apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: monapp
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: users-service
  namespace: monapp
spec:
  selector:
    app: users-service
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: products-service
  namespace: monapp
spec:
  selector:
    app: products-service
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: orders-service
  namespace: monapp
spec:
  selector:
    app: orders-service
  ports:
    - protocol: TCP
      port: 8003
      targetPort: 8003
  type: ClusterIP

  

apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: monapp
spec:
  selector:
    app: gateway-service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer
