apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: monapp
  labels:
    app: postgres
spec:
  selector:
    app: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: users-service
  namespace: monapp
  labels: { app: users-service }
spec:
  selector: { app: users-service }
  ports:
    - name: http
      port: 8001
      targetPort: 8001

---
apiVersion: v1
kind: Service
metadata:
  name: products-service
  namespace: monapp
  labels: { app: products-service }
spec:
  selector: { app: products-service }
  ports:
    - name: http
      port: 8002
      targetPort: 8002

---
apiVersion: v1
kind: Service
metadata:
  name: orders-service
  namespace: monapp
  labels: { app: orders-service }
spec:
  selector: { app: orders-service }
  ports:
    - name: http
      port: 8003
      targetPort: 8003

  

apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: monapp
  labels: { app: gateway-service }
spec:
  selector: { app: gateway-service }
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  type: LoadBalancer
