# Déploiement Users Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-service
  namespace: monapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-service
  template:
    metadata:
      labels:
        app: users-service
    spec:
      initContainers:
        - name: wait-for-db
          image: busybox:1.28
          command: ['sh', '-c', 'until nc -z db 5432; do echo "Waiting for PostgreSQL..."; sleep 2; done']
      containers:
        - name: users-service
          image: d0eb58e49125.ngrok-free.app/deploy:15-users-service
          envFrom:
            - configMapRef:
                name: app-config
          ports:
            - containerPort: 8001
          readinessProbe:
            httpGet:
              port: 8001
            initialDelaySeconds: 10
            periodSeconds: 5