# Déploiement Users Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-service
  namespace: monapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-service
  template:
    metadata:
      labels:
        app: users-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8001"
        prometheus.io/path: "/metrics"
    spec:
      initContainers:
        - name: wait-for-db
          image: busybox:1.28
          command: ['sh', '-c', 'until nc -z db 5432; do echo "Waiting for PostgreSQL..."; sleep 2; done']
      containers:
        - name: users-service
          image: a52344538257.ngrok-free.app/deploy:16-users-service
          envFrom:
            - configMapRef:
                name: app-config
          ports:
            - containerPort: 8001
          readinessProbe:
            httpGet:
              port: 8001
            initialDelaySeconds: 10
            periodSeconds: 5